name: Build

on:
  push:

jobs:
  build_tracker:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Snowplow.Tracker dependencies
      run: dotnet restore Snowplow.Tracker.sln

    - name: Build Snowplow.Tracker
      run: dotnet build Snowplow.Tracker.sln --no-restore -c Release

    - name: Test Snowplow.Tracker
      run: dotnet test Snowplow.Tracker.Tests/Snowplow.Tracker.Tests.csproj --no-build --verbosity normal -c Release

  build_extensions:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup nuget
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '5.x'

    - name: Enable MSMQ
      run: Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Server -All     

    - name: NuGet Restore
      run: nuget restore Snowplow.Tracker.PlatformExtensions.sln

    - name: Build Snowplow.Tracker.PlatformExtensions
      run: msbuild Snowplow.Tracker.PlatformExtensions.sln /property:Configuration=Release

    - name: Test Snowplow.Tracker.PlatformExtensions
      run: '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer:Snowplow.Tracker.PlatformExtensions\DotnetTests\bin\Release\DotnetTests.dll'
